export interface BiblicalEvent {
  readonly reference: string;
  readonly month: number;
  readonly day: number | null;
  readonly day_range: readonly [number, number] | null;
  readonly keyword: string;
  readonly context: string;
}

export const BIBLICAL_EVENTS: readonly BiblicalEvent[] = [
  { reference: "Genesis 7:11", month: 2, day: 17, day_range: null, keyword: "Déluge", context: "Début du déluge — toutes les sources du grand abîme jaillissent" },
  { reference: "Genesis 8:4", month: 7, day: 17, day_range: null, keyword: "Repos", context: "L'arche s'arrête sur les montagnes d'Ararat" },
  { reference: "Genesis 8:5", month: 10, day: 1, day_range: null, keyword: "Déluge", context: "Les eaux diminuent, les sommets des montagnes deviennent visibles" },
  { reference: "Genesis 8:13", month: 1, day: 1, day_range: null, keyword: "Assèchement", context: "Les eaux s'assèchent sur la terre (601e année de Noé)" },
  { reference: "Genesis 8:14", month: 2, day: 27, day_range: null, keyword: "Restauration", context: "La terre est complètement sèche" },
  { reference: "Exodus 12:2-3", month: 1, day: 10, day_range: null, keyword: "Préparation", context: "Choix de l'agneau pascal — ce mois sera le premier de l'année" },
  { reference: "Exodus 12:6", month: 1, day: 14, day_range: null, keyword: "Délivrance", context: "Immolation de l'agneau pascal au soir" },
  { reference: "Exodus 12:15", month: 1, day: 15, day_range: null, keyword: "Départ", context: "Départ effectif d'Égypte — premier jour des pains sans levain" },
  { reference: "Exodus 12:18", month: 1, day: 14, day_range: [14, 21], keyword: "Délivrance", context: "Fête des pains sans levain (du 14e au 21e jour)" },
  { reference: "Exodus 16:1", month: 2, day: 15, day_range: null, keyword: "Murmure", context: "Murmures avant la manne dans le désert de Sin" },
  { reference: "Exodus 19:1", month: 3, day: 15, day_range: null, keyword: "Arrivée", context: "Arrivée au désert de Sinaï — même jour que le départ d'Égypte" },
  { reference: "Exodus 23:16", month: 3, day: null, day_range: null, keyword: "Moisson", context: "Fête de la moisson (Shavouot), célébrée avec les prémices des récoltes" },
  { reference: "Leviticus 23:15-21", month: 3, day: 6, day_range: null, keyword: "Semaines", context: "Fête des Semaines (Shavouot), décompte de 50 jours après l'offrande de l'omer, avec offrandes de pain et sacrifices" },
  { reference: "Numbers 28:26-31", month: 3, day: 6, day_range: null, keyword: "Prémices", context: "Jour des prémices (Shavouot), sainte convocation avec offrandes spéciales pour la fête des Semaines" },
  { reference: "Deuteronomy 16:9-12", month: 3, day: 6, day_range: null, keyword: "Semaines", context: "Fête des Semaines (Shavouot), décompte de sept semaines depuis le début de la moisson, célébrée avec offrandes et joie communautaire" },
  { reference: "Exodus 40:2", month: 1, day: 1, day_range: null, keyword: "Tabernacle", context: "Ordre d'élever le tabernacle le premier jour du premier mois" },
  { reference: "Exodus 40:17", month: 1, day: 1, day_range: null, keyword: "Tabernacle", context: "Érection effective du tabernacle (deuxième année)" },
  { reference: "Leviticus 23:5", month: 1, day: 14, day_range: null, keyword: "Pâque", context: "La Pâque de l'Éternel commence au crépuscule le quatorzième jour" },
  { reference: "Leviticus 23:6", month: 1, day: 15, day_range: [15, 21], keyword: "Azymes", context: "Début de la fête des pains sans levain — sept jours" },
  { reference: "Leviticus 23:24", month: 7, day: 1, day_range: null, keyword: "Trompettes", context: "Jour du son de la trompette — mémorial et sainte convocation" },
  { reference: "Leviticus 23:27", month: 7, day: 10, day_range: null, keyword: "Expiation", context: "Jour de l'expiation — sainte convocation et affliction des âmes" },
  { reference: "Leviticus 23:34", month: 7, day: 15, day_range: [15, 21], keyword: "Cabanes", context: "Fête des cabanes (Tabernacles) — sept jours" },
  { reference: "Leviticus 23:39", month: 7, day: 15, day_range: [15, 22], keyword: "Cabanes", context: "Fête des cabanes avec huitième jour d'assemblée solennelle" },
  { reference: "I Enoch 60:1", month: 7, day: 14, day_range: null, keyword: "Vision de Noé", context: "Léviathan et Béhémoth" },
  { reference: "Numbers 1:1", month: 2, day: 1, day_range: null, keyword: "Dénombrement", context: "Premier recensement dans le désert de Sinaï (deuxième année, deuxième mois)" },
  { reference: "Numbers 9:1", month: 1, day: 1, day_range: null, keyword: "Pâque", context: "Instruction de la Pâque dans le désert (deuxième année, premier mois)" },
  { reference: "Numbers 9:11", month: 2, day: 14, day_range: null, keyword: "Pâque", context: "Seconde Pâque pour ceux qui étaient impurs" },
  { reference: "Numbers 10:11", month: 2, day: 20, day_range: null, keyword: "Départ", context: "Départ du Sinaï — la nuée s'élève (deuxième année)" },
  { reference: "Numbers 20:1", month: 1, day: 1, day_range: null, keyword: "Mort", context: "Mort de Miriam à Kadès" },
  { reference: "Numbers 33:3", month: 1, day: 15, day_range: null, keyword: "Départ", context: "Départ de Ramsès — lendemain de la Pâque" },
  { reference: "Numbers 33:38", month: 5, day: 1, day_range: null, keyword: "Mort", context: "Mort d'Aaron sur le mont Hor (40e année)" },
  { reference: "Deuteronomy 1:3", month: 11, day: 1, day_range: null, keyword: "Discours", context: "Moïse parle au peuple" },
  { reference: "Joshua 4:19", month: 1, day: 10, day_range: null, keyword: "Traversée", context: "Entrée en Canaan par le Jourdain" },
  { reference: "1 Kings 6:1", month: 2, day: 1, day_range: null, keyword: "Construction", context: "Début du temple de Salomon (4e année, 2e mois)" },
  { reference: "1 Kings 6:38", month: 8, day: 1, day_range: null, keyword: "Achèvement", context: "Achèvement du temple de Salomon (7 ans)" },
  { reference: "1 Kings 8:2", month: 7, day: 15, day_range: null, keyword: "Dédicace", context: "Dédicace du temple à la fête des cabanes" },
  { reference: "1 Kings 12:32", month: 8, day: 15, day_range: null, keyword: "Apostasie", context: "Fausse fête de Jéroboam" },
  { reference: "2 Chronicles 7:10", month: 7, day: 23, day_range: null, keyword: "Congé", context: "Fin de la célébration de la dédicace" },
  { reference: "2 Chronicles 29:17", month: 1, day: 1, day_range: [1, 16], keyword: "Purification", context: "Purification du temple sous Ézéchias" },
  { reference: "2 Chronicles 30:2", month: 2, day: 14, day_range: null, keyword: "Pâque", context: "Pâque retardée d'Ézéchias" },
  { reference: "2 Chronicles 35:1", month: 1, day: 14, day_range: null, keyword: "Pâque", context: "Grande Pâque de Josias" },
  { reference: "Ezra 3:1", month: 7, day: 1, day_range: null, keyword: "Autel", context: "Reconstruction de l'autel après le retour" },
  { reference: "Ezra 3:6", month: 7, day: 1, day_range: null, keyword: "Offrande", context: "Premières offrandes après le retour" },
  { reference: "Ezra 6:15", month: 12, day: 3, day_range: null, keyword: "Temple", context: "Achèvement du second temple" },
  { reference: "Ezra 7:9", month: 1, day: 1, day_range: null, keyword: "Voyage", context: "Début du voyage d'Esdras" },
  { reference: "Ezra 7:9", month: 5, day: 1, day_range: null, keyword: "Arrivée", context: "Arrivée d'Esdras à Jérusalem" },
  { reference: "Ezra 10:16-17", month: 10, day: 1, day_range: null, keyword: "Enquête", context: "Enquête sur les mariages mixtes" },
  { reference: "Nehemiah 1:1", month: 9, day: 1, day_range: null, keyword: "Nouvelles", context: "Néhémie apprend l'état de Jérusalem" },
  { reference: "Nehemiah 2:1", month: 1, day: 1, day_range: null, keyword: "Permission", context: "Néhémie obtient la permission de rebâtir" },
  { reference: "Nehemiah 6:15", month: 6, day: 25, day_range: null, keyword: "Muraille", context: "Achèvement de la muraille de Jérusalem" },
  { reference: "Nehemiah 8:2", month: 7, day: 1, day_range: null, keyword: "Lecture", context: "Lecture de la Loi par Esdras" },
  { reference: "Nehemiah 8:14", month: 7, day: 15, day_range: [15, 21], keyword: "Cabanes", context: "Célébration de la fête des cabanes" },
  { reference: "Esther 2:16", month: 10, day: 1, day_range: null, keyword: "Rencontre", context: "Esther rencontre le roi (mois de Tébeth)" },
  { reference: "Esther 3:12", month: 1, day: 13, day_range: null, keyword: "Sort", context: "Tirage au sort durant le premier mois & Convocation des secrétaires du roi et rédaction du décret d'extermination le 13." },
  { reference: "Esther 3:13", month: 12, day: 13, day_range: null, keyword: "Complot", context: "Décret d'Haman pour détruire les Juifs" },
  { reference: "Esther 8:12", month: 12, day: 13, day_range: null, keyword: "Défense", context: "Contre-décret pour les Juifs" },
  { reference: "Esther 9:1", month: 12, day: 13, day_range: null, keyword: "Victoire", context: "Jour du combat et de la victoire des Juifs" },
  { reference: "Esther 9:17", month: 12, day: 14, day_range: null, keyword: "Repos", context: "Jour de repos et de festin" },
  { reference: "Esther 9:18", month: 12, day: 15, day_range: null, keyword: "Pourim", context: "Jour de célébration de Pourim" },
  { reference: "Jeremiah 1:3", month: 5, day: 10, day_range: null, keyword: "Exil", context: "Fin du règne de Jojakim et exil" },
  { reference: "Jeremiah 36:9", month: 9, day: 5, day_range: null, keyword: "Jeûne", context: "Jeûne proclamé, lecture du rouleau" },
  { reference: "Jeremiah 39:2", month: 4, day: 9, day_range: null, keyword: "Brèche", context: "Brèche ouverte dans la muraille de Jérusalem" },
  { reference: "Jeremiah 52:4", month: 10, day: 10, day_range: null, keyword: "Siège", context: "Début du siège de Jérusalem par Nebucadnetsar" },
  { reference: "Jeremiah 52:6", month: 4, day: 9, day_range: null, keyword: "Famine", context: "Famine sévère pendant le siège" },
  { reference: "Jeremiah 52:12", month: 5, day: 10, day_range: null, keyword: "Destruction", context: "Destruction du temple par Nebuzaradan" },
  { reference: "Jeremiah 52:31", month: 12, day: 25, day_range: null, keyword: "Libération", context: "Libération de Jojakin de prison" },
  { reference: "Ezekiel 1:1-2", month: 4, day: 5, day_range: null, keyword: "Révélation", context: "Vision des cieux ouverts (5e année d'exil)" },
  { reference: "Ezekiel 8:1", month: 6, day: 5, day_range: null, keyword: "Transport", context: "Vision — transport à Jérusalem" },
  { reference: "Ezekiel 20:1", month: 5, day: 10, day_range: null, keyword: "Parole", context: "Parole aux anciens d'Israël" },
  { reference: "Ezekiel 24:1", month: 10, day: 10, day_range: null, keyword: "Parabole", context: "Parabole de la marmite bouillante — début du siège" },
  { reference: "Ezekiel 29:1", month: 10, day: 12, day_range: null, keyword: "Jugement", context: "Jugement contre l'Égypte" },
  { reference: "Ezekiel 29:17", month: 1, day: 1, day_range: null, keyword: "Consolation", context: "Prophétie sur Nebucadnetsar et l'Égypte" },
  { reference: "Ezekiel 30:20", month: 1, day: 7, day_range: null, keyword: "Bras", context: "Jugement sur le bras du Pharaon" },
  { reference: "Ezekiel 31:1", month: 3, day: 1, day_range: null, keyword: "Allégorie", context: "Allégorie de l'Assyrie comme cèdre" },
  { reference: "Ezekiel 32:1", month: 12, day: 1, day_range: null, keyword: "Lamentation", context: "Lamentation sur le Pharaon" },
  { reference: "Ezekiel 33:21", month: 10, day: 5, day_range: null, keyword: "Nouvelles", context: "La chute de Jérusalem parvient aux exilés" },
  { reference: "Ezekiel 40:1", month: 1, day: 10, day_range: null, keyword: "Temple", context: "Vision du temple idéal" },
  { reference: "Daniel 10:4, 10:2-3", month: 1, day: 24, day_range: null, keyword: "Vision", context: "Vision surnaturelle" },
  { reference: "Haggai 1:1", month: 6, day: 1, day_range: null, keyword: "Exhortation", context: "Parole pour rebâtir le temple" },
  { reference: "Haggai 1:15", month: 6, day: 24, day_range: null, keyword: "Travail", context: "Début des travaux de reconstruction du temple" },
  { reference: "Haggai 2:1", month: 7, day: 21, day_range: null, keyword: "Encouragement", context: "Encouragement divin pendant la fête des cabanes" },
  { reference: "Haggai 2:10", month: 9, day: 24, day_range: null, keyword: "Bénédiction", context: "Promesse de bénédiction" },
  { reference: "Haggai 2:20", month: 9, day: 24, day_range: null, keyword: "Zorobabel", context: "Promesse à Zorobabel" },
  { reference: "Zechariah 1:1", month: 8, day: 1, day_range: null, keyword: "Appel", context: "Appel à revenir à l'Éternel" },
  { reference: "Zechariah 1:7", month: 11, day: 24, day_range: null, keyword: "Songes", context: "Visions nocturnes de chevaux" },
  { reference: "Zechariah 7:1", month: 9, day: 4, day_range: null, keyword: "Question", context: "Question sur le jeûne et le deuil" },
  { reference: "2 Kings 25:1", month: 10, day: 10, day_range: null, keyword: "Siège", context: "Début du dernier siège de Jérusalem" },
  { reference: "2 Kings 25:3", month: 4, day: 9, day_range: null, keyword: "Famine", context: "Famine sévère dans la ville" },
  { reference: "2 Kings 25:8", month: 5, day: 7, day_range: null, keyword: "Destruction", context: "Nebuzaradan vient à Jérusalem" },
  { reference: "2 Kings 25:25", month: 7, day: 1, day_range: null, keyword: "Meurtre", context: "Assassinat de Guedalia" },
  { reference: "Zechariah 8:19", month: 4, day: 17, day_range: null, keyword: "Jeûne", context: "Jeûne du quatrième mois" },
  { reference: "Zechariah 8:19", month: 5, day: 9, day_range: null, keyword: "Jeûne", context: "Jeûne du cinquième mois" },
  { reference: "Zechariah 8:19", month: 7, day: 3, day_range: null, keyword: "Jeûne", context: "Jeûne du septième mois" },
  { reference: "Zechariah 8:19", month: 10, day: 10, day_range: null, keyword: "Jeûne", context: "Jeûne du dixième mois" },
  { reference: "Matarii i ni a", month: 2, day: 29, day_range: null, keyword: "Polynésie", context: "Dates polynésiennes" },
  { reference: "Matarii i raro", month: 8, day: 28, day_range: null, keyword: "Polynésie", context: "Dates polynésiennes" },
  { reference: "Matariki", month: 9, day: 28, day_range: null, keyword: "Polynésie", context: "Dates polynésiennes" },
  { reference: "Matariki", month: 9, day: 29, day_range: null, keyword: "Polynésie", context: "Dates polynésiennes" },
  { reference: "Matariki", month: 9, day: 30, day_range: null, keyword: "Polynésie", context: "Dates polynésiennes" },
  { reference: "Matariki", month: 10, day: 1, day_range: null, keyword: "Polynésie", context: "Dates polynésiennes" },
] as const;